#ifndef _WAWO_CONFIG_PLATFORM_H_
#define _WAWO_CONFIG_PLATFORM_H_

#define _WAWO_PLATFORM_WIN		1
#define _WAWO_PLATFORM_POSIX	2

#if defined(WIN32) || defined(OS_WIN32) || defined WIN32_LEAN_AND_MEAN
	#define WAWO_PLATFORM_WIN		1
	#define WAWO_PLATFORM			_WAWO_PLATFORM_WIN
	#define WAWO_PLATFORM_STR		win
#elif defined(OS_IOS) || defined(OS_LINUX) || defined(OS_IPHONE)
	#define WAWO_PLATFORM_POSIX		1
	#define WAWO_PLATFORM			_WAWO_PLATFORM_POSIX
	#define WAWO_PLATFORM_STR		posix
#else
	#error
#endif

#define IS_WIN()	(WAWO_PLATFORM==_WAWO_PLATFORM_WIN)
#define IS_POSIX()	(WAWO_PLATFORM==_WAWO_PLATFORM_POSIX)

#define _WAWO_ADDRESS_MODEL_X32	32
#define _WAWO_ADDRESS_MODEL_X64	64

#if defined(WIN32) || defined(WIN32_LEAN_AND_MEAN) || defined(ADDRESS_MODEL_32)
	#define WAWO_ADDRESS_MODEL		_WAWO_ADDRESS_MODEL_X32
#elif defined (ADDRESS_MODEL_64)
	#define WAWO_ADDRESS_MODEL		_WAWO_ADDRESS_MODEL_X64
#endif


#define IS_X32() (WAWO_ADDRESS_MODEL==_WAWO_ADDRESS_MODEL_X32)
#define IS_X64() (WAWO_ADDRESS_MODEL==_WAWO_ADDRESS_MODEL_X64)


#define WAWO_PLATFORM_HEADER(path)				WAWO_PLATFORM_HEADER1(path, WAWO_PLATFORM_STR)
#define WAWO_PLATFORM_HEADER1(path,platform)	WAWO_PLATFORM_HEADER2(path,platform)
#define WAWO_PLATFORM_HEADER2(path,platform)	<path##_##platform##_.h>

#include WAWO_PLATFORM_HEADER(wawo/config/platform/platform)

#endif
